### ISSUE TITLE
Change style of "Read more" button on team.html

### ISSUE THREAD

**Issue by rahyoung** [onewaypath/onewaypath.com-bootstrap#13]
- [x] update to the latest version of dev1 branch
- [x] change the style of the "Read more" buttons on team.html to match the style of the "View details" button on projects.html
- [x] push changes to dev1 branch in a commit for only this issue

**Comment by dynamicdreamz1** [comment]
Change style of "Read more" button on team.html => done and updated in dev1 branch

**Comment by rahyoung** [comment]
- [x] Button styles do not match. On team page it needs to be square with rounded corners like on projects page.

**Comment by dynamicdreamz1** [comment]
please check this video both button style are same => https://watch.screencastify.com/v/4ARhArlS1bf2C9FRoqzJ
width is different of both button due to text length.

**Comment by rahyoung** [comment]
Buttons are not the same on chrome. Please make your you test across browsers. 
- [x] please update to make sure button styles are consistent. 

![image](https://user-images.githubusercontent.com/50812666/167790426-7236c94f-f7f4-47af-8a5f-188abada8957.png)

**Comment by dynamicdreamz1** [comment]
> * please update to make sure button styles are consistent.

we have chack in iphone chrome this is done please check it. => https://github.com/onewaypath/onewaypath.com-bootstrap/commit/8089f77a44d92be8dc9d366317127ccf0b9bf8df
