### ISSUE TITLE
Copy Buddhavipassana site to On-Num

### ISSUE THREAD

**Issue by rahyoung** [onewaypath/onewaypath.com-bootstrap#14]
**- [ ] IMPORTANT: Do this task only after all the tasks are completed for the Buddhavipassana project otherwise not all of the desired updates will be copied over**
- [x] update to the latest version of dev1 branch
- [x] copy the entire buddhavipassana folder
- [x] rename the folder to on-num
- [x] add a "View details" button to the "On-Num Meditation Centre" item on the projects.html page and point the link to on-num/overview.html
- [x] In all pages within the on-num folder replace "Buddhavipassana" with "On-Num" in the title tag and the nav bar header
- [x] In on-num/accommodations.html delete the section commented with "!-- photo album of accomodation photos "
- [x] In on-num/overview.html delete the div class="container marketing" tag and its contents
- [x] In on-num/teachers.html delete the last feature item for Sandra Young (the div class="row featurette" tag and its contents) and retain the first two feature items for Miriam Young and Alex Young
- [x] push changes back to dev1 branch with a commit for this issue only

**Comment by dynamicdreamz1** [comment]
https://github.com/onewaypath/onewaypath.com-bootstrap/issues/14 **=> All changes done and updated on dev1**
