### ISSUE TITLE
Create @Millen Road Website

### ISSUE THREAD

**Issue by rahyoung** [onewaypath/onewaypath.com-bootstrap#15]
- [x] update to the latest version of dev1 branch
- [x] copy the Buddhavipassana folder and rename it to MillenRoad
- [x] in the MillenRoad folder delete all the html files except for accommodations.html, overview.html and the practice.html
- [x] update the sub-menu so that it contains the following items:
       - Design -> link to MillenRoad/design.html
       - Parking -> link to MillenRoad/parking.html
       - Diligence -> link to MillenRoad/diligence.html
- [x] On the projects.html page add a "View details" button to the `One Way Path @Millen Road` item and link it to MillenRoad/design.html
- [x] push your changes back to dev1 branch in a commit for this issue only

**Comment by dynamicdreamz1** [comment]
Create @Millen Road Website #15 **=> Done and updated on dev1**
