### ISSUE TITLE
Add design page

### ISSUE THREAD

**Issue by rahyoung** [onewaypath/onewaypath.com-bootstrap#16]
- [x] IMPORTANT: you have to complete issue #15 before you complete this issue
- [x] update to the latest version of dev1 branch
- [x] rename the MillenRoad/accomodations.html page to MillenRoad/design.html
- [x] change the title to `@Millen Road | Design`
- [x] change the title in the main nav bar to `@Millen Road`
- [x] on the sub-menu make design the active page
- [x] push your changes back to dev1 branch in a commit for this issue only

**Comment by dynamicdreamz1** [comment]
Add design page #16 **=> Done all and updated on Dev1**
