### ISSUE TITLE
Add parking page

### ISSUE THREAD

**Issue by rahyoung** [onewaypath/onewaypath.com-bootstrap#17]
- [x] IMPORTANT: you have to complete issue #15 before you complete this issue
- [x] update to the latest version of dev1 branch
- [x] rename the MillenRoad/the-practice.html page to MillenRoad/parking.html
- [x] change the title to `@Millen Road | Parking`
- [x] change the title in the main nav bar to `@Millen Road`
- [x] update the sub-menu to match the one completed in issue #15 
- [x] make parking the active item on the sub-menu
- [x] replace the contents of the main tag with an embedded video. The video to embed is here: https://www.youtube.com/watch?v=lDbMnNMdFFg
- [x] push your changes back to dev1 branch in a commit for this issue only

**Comment by dynamicdreamz1** [comment]
Add parking page #17 **=> Done all and updated in Dev1**
