### ISSUE TITLE
Add diligence page

### ISSUE THREAD

**Issue by rahyoung** [onewaypath/onewaypath.com-bootstrap#18]
- [x] IMPORTANT: you have to complete issue #15 before you complete this issue
- [x] update to the latest version of dev1 branch
- [x] copy the file ayoung.html to the MillenRoad folder and rename it to MillenRoad/diligence.html
- [x] change the title to `@Millen Road | Diligence`
- [x] change the title in the main nav bar to `@Millen Road`
- [x] update the sub-menu to match the one completed in issue #15 
- [x] make diligence the active item on the sub-menu
- [x] push your changes back to dev1 branch in a commit for this issue only

**Comment by dynamicdreamz1** [comment]
Add diligence page #18 **=> Done all and updated on Dev1**
