### ISSUE TITLE
Change margins of the-practice.html, faq.html and daily-schedule.html

### ISSUE THREAD

**Issue by rahyoung** [onewaypath/onewaypath.com-bootstrap#2]
- [x] Update your local repo to the latest version of the dev1 branch
- [x] please adjust the horizontal page margins of buddhavipassana/the-practice.html to match the horizontal page margins of buddhavipassana/overview.html.
- [x] Push your changes back to the dev1 branch on a commit for this issue only

**Comment by onewaypath** [comment]
- [ ] Update your local repo to the latest version of the dev1 branch
- [ ] please adjust the horizontal page margins of buddhavipassana/the-practice.html to match the horizontal page margins of buddhavipassana/overview.html.
- [ ] Push your changes back to the dev1 branch on a commit for this issue only

**Comment by rahyoung** [comment]
I should have been more specific. I mean to refer to the text margins. They should be consistent throughout the site. Please reduce them on mobile for the following pages so that the text margins are the same as overview.html:

- [x] the-practice.html
- [x] FAQ.html

![image](https://user-images.githubusercontent.com/50812666/167367327-401e571b-6e1c-4511-8674-e3c427689768.png)

![image](https://user-images.githubusercontent.com/50812666/167367698-5288c139-453b-4bd0-9d1e-c8bcb894f274.png)

![image](https://user-images.githubusercontent.com/50812666/167367726-5748eba6-2040-448e-87b6-e47547905269.png)

**Comment by rahyoung** [comment]
- [ ] please also update margins on daily-schedule.html

**Comment by dynamicdreamz1** [comment]
update margins on daily-schedule.html => Done

**Comment by rahyoung** [comment]
> update margins on daily-schedule.html => Done

@dynamicdreamz1 , please note you can tick the box next to the task to indicate it's finished instead of re-writing it.
