### ISSUE TITLE
Add team page

### ISSUE THREAD

**Issue by rahyoung** [onewaypath/onewaypath.com-bootstrap#20]
- [x] IMPORTANT: you have to complete issue #15 before you complete this issue
- [x] update to the latest version of dev1 branch
- [x] push your changes back to dev1 branch in a commit for this issue only

**Comment by rahyoung** [comment]
- [x] You need to add your commit to the task

**Comment by dynamicdreamz1** [comment]
This all changes is already done and push on dev1 branch

**Comment by rahyoung** [comment]
- [x] Please link your commit to this issue on GitHub so that I can see the changes.

**Comment by dynamicdreamz1** [comment]
Link of commit:-
https://github.com/onewaypath/onewaypath.com-bootstrap/commit/200d6dba432d3b7a31560bbb0c4e269043f166cf
