### ISSUE TITLE
Fix submenu dropdown bug

### ISSUE THREAD

**Issue by rahyoung** [onewaypath/onewaypath.com-bootstrap#24]
On the submenu, if one of the dropdown menus is open and the user clicks on another dropdown, the text does not shift down to reveal the new dropdown. Please see attached screen video:

- [x] update to the latest version of dev1 branch
- [x] ensure text shifts down when dropdown is selected even when another dropdown is already selected. 
- [x] push your changes back to dev1 branch in a commit for this issue only and include `fixes #24` in the commit message

https://user-images.githubusercontent.com/50812666/168643834-0c1a0392-d0c0-46ef-af11-61de84775345.mov

**Comment by dynamicdreamz1** [comment]
Fix submenu dropdown bug #24 
=> fixes #24
