### ISSUE TITLE
Update all pages so that the submenu item for the active page is displayed

### ISSUE THREAD

**Issue by rahyoung** [onewaypath/onewaypath.com-bootstrap#25]
Only the first few items on the submenu are visible when the page is opened. Therefore, if for, example, the FAQ page is selected, the FAQ item on the submenu is not visible (see attached video). The menu needs to be adjusted so that it will display the menu item for the active page. This means that for example, if FAQ page is active, the menu will start so that the FAQ item on the right  is visible. 

- [x] update to the latest version of dev1 branch
- [x] update all pages so that the submenu item for the active page is displayed
- [x] push your changes back to dev1 branch in a commit for this issue only and include `fixes #25` in the commit message

https://user-images.githubusercontent.com/50812666/168656223-b8d55cb6-418f-49b0-b415-ca7bb1cf56b2.mov

**Comment by dynamicdreamz1** [comment]
Update all pages so that the submenu item for the active page is displayed #25
=> This is done please see video => https://watch.screencastify.com/v/n8TaF5RMCh4s1sN000PH

**Comment by rahyoung** [comment]
I see that you changed the order of the submenu for each page. I find this confusing as the order keeps changing for each page the user selects. 
- [x] Can you make the menu in the same order for every page and just change the scroll state so that the menus is scrolled so that the menu item for the active page is visible?

**Comment by dynamicdreamz1** [comment]
Can you make the menu in the same order for every page and just change the scroll state so that the menus is scrolled so that the menu item for the active page is visible? => This is not possible, if you want to show all active menu item on first so order changes is necessary. other way is remove scroll and show all item in 1st and 2nd row.

**Comment by rahyoung** [comment]
- [x] Ok please revert so that items in sub menu are in the same order on every page (the original order)

**Comment by dynamicdreamz1** [comment]
Ok please revert so that items in sub menu are in the same order on every page (the original order) => This is done
[fixes](https://github.com/onewaypath/onewaypath.com-bootstrap/commit/dd15b0adeba48ace5d8b85b7464b3bcab7157d2b) https://github.com/onewaypath/onewaypath.com-bootstrap/issues/25
