### ISSUE TITLE
Fix submenu scroll effect

### ISSUE THREAD

**Issue by rahyoung** [onewaypath/onewaypath.com-bootstrap#26]
When the user scrolls the submenu, one of the items turns blue. Please ensure this does not happen. See attached video. 

- [x] update to the latest version of dev1 branch
- [x] ensure that items do not change colour when submenu is scrolled. 
- [x] push your changes back to dev1 branch in a commit for this issue only and include `fixes #26` in the commit message

https://user-images.githubusercontent.com/50812666/168702276-b47e153c-cd7b-4db1-88d7-dc61b1444a56.MOV

**Comment by dynamicdreamz1** [comment]
This is done but when you touch on menu text hover effect is active blue color => [fixes](https://github.com/onewaypath/onewaypath.com-bootstrap/commit/52f04b1c044c682a1eb2868ecc70376fa8f5a4a6) https://github.com/onewaypath/onewaypath.com-bootstrap/issues/26
