### ISSUE TITLE
Check active page indicators

### ISSUE THREAD

**Issue by rahyoung** [onewaypath/onewaypath.com-bootstrap#27]
- [x] update to the latest version of dev1 branch
- [x] please check all pages on all three site to make sure that the submenu item is set to active for the current page. I noticed that on-num has several pages where the correct submenu item is not set active
- [x] push your changes back to dev1 branch in a commit for this issue only and include `fixes #27`  in the commit message

**Comment by dynamicdreamz1** [comment]
This is done => [fixes](https://github.com/onewaypath/onewaypath.com-bootstrap/commit/445c9471adc4fa85d32854f107c0d524dea54317) https://github.com/onewaypath/onewaypath.com-bootstrap/issues/27
