### ISSUE TITLE
Update logo on all buddhavipassana pages

### ISSUE THREAD

**Issue by rahyoung** [onewaypath/onewaypath.com-bootstrap#5]
- [x] Update your local repo to the latest version of the dev1 branch 
- [x] On all pages within the buddhavipassana folder delete the logo on the main nav bar and change the font of "Buddhavipassana" to match the font used for the heading at buddhavipassana.ca. 
- [x]  push your changes back to the dev1 branch on a commit for this issue only

**Comment by rahyoung** [comment]
Since this is custom css that is common to all Buddhavipassana pages please do the following:
- [x] Move the css to a separate file called Buddhavipassana/assets/css/header.css

Also where possible I prefer to avoid using the class element. When html becomes dynamic class element is harder to manage. Therefore, 
- [x] Target the h1 tag in the header instead of using class

**Comment by rahyoung** [comment]
On all pages in Buddhavipassana folder
- [x] target the h1 tag inside the header tag without using the class element
- [x] remove the extraneous span tag around the h1 element

**Comment by dynamicdreamz1** [comment]
On all pages in Buddhavipassana folder

 target the h1 tag inside the header tag without using the class element => Done
 remove the extraneous span tag around the h1 element => Done

**Comment by rahyoung** [comment]
- [x] @dynamicdreamz1, please link your commit so that I can quickly review how you made the update.

**Comment by rahyoung** [comment]
- [x] Did you remove extraneous spam tag? I don't see commit and task is not checked.

**Comment by dynamicdreamz1** [comment]
We have remove span on all page of  buddhavipassana (we have already remove span)

**Comment by rahyoung** [comment]
- [x] You need to
Link your commit so that I can see that the tag was removed.

**Comment by dynamicdreamz1** [comment]
https://github.com/onewaypath/onewaypath.com-bootstrap/commit/0d3514fe0be559e56bf9335a6dffd51783403272
https://github.com/onewaypath/onewaypath.com-bootstrap/commit/e0f49cf1ca38ee8c4c3f4198fdf80e6cb4b661a2
https://github.com/onewaypath/onewaypath.com-bootstrap/commit/7f4a457f798ad0017ae2f872c53878e11823c236
https://github.com/onewaypath/onewaypath.com-bootstrap/commit/dc72973387b56d546d3c8140aa59260c146da6f8
https://github.com/onewaypath/onewaypath.com-bootstrap/commit/b343c69429811d04dca18c9a1caee6c90942cea2
https://github.com/onewaypath/onewaypath.com-bootstrap/commit/87a46ce5e8e6f7d8126d94163fe4cfcf0ec38b2d
https://github.com/onewaypath/onewaypath.com-bootstrap/commit/9bc647856c84c5a74ec7e0b04680de81f99c625f
https://github.com/onewaypath/onewaypath.com-bootstrap/commit/0231e861fb529a9c8487d0a2cd3ded8db142d7af
https://github.com/onewaypath/onewaypath.com-bootstrap/commit/221c5b839b787658eb44e0ab7afdb73f5e88e45c
This is link that i was committed before 2 days please chack.
