### ISSUE TITLE
Add links to 2018 Photo Page

### ISSUE THREAD

**Issue by rahyoung** [onewaypath/onewaypath.com-bootstrap#53]
I have created a new page at on-num/photo-gallery-2018.html. This requires the following changes:

- change the travel menu item to "Photos" and the existing sub-menu items to "Travel Photos (Colour)" and "Travel Photos (B&W)"
- add a link as the first sub-menu item under "Photos" called "Blessing Ceremony (2018)" linking to on-num/photo-gallery-2018.html
- The above needs to be done on each of the pages of the On-Nūm site. I have already done it for overview.html as an example (commit is referenced to this issue). Please complete the other pages. 
- You can push your changes back to dev1 in a single commit referenced to this issue for all the pages.

- [x] overview.html
- [x] the-practice.html
- [x] accomodations.html
- [x] daily-schedule.html
- [x] teachers.html
- [x] spiritual-leaders.html
- [x] photo-gallery-bw.html
- [x] photo-gallery-colour.html
- [x] photo-gallery-2018.html
- [x] faq.html

**Comment by dynamicdreamz1** [comment]
https://github.com/onewaypath/onewaypath.com-bootstrap/commit/ad8d7b2569320b0236f3bf79acf565b5a5fc883e => done update all link on all on-num pages
