### ISSUE TITLE
Remove "class=featurette-heading" from pages that use features template

### ISSUE THREAD

**Issue by rahyoung** [onewaypath/onewaypath.com-bootstrap#6]
- [x] update to the latest version of dev1 branch
- [x] projects.html uses the features template. Each of the items has a heading in the class="featurette-heading". This class provides optimal spacing of the text next to the photo. We would like to remove the class so that the h2 font matches the h2 font on the rest of the site without affecting the spacing. Please edit the assets/css/carousel.css file so that the correct spacing is applied to the h2 tag inside the class="container marketing"
- [x] remove the "class=featurette-heading" so that the font matches the h2 font on the rest of the site
- [x]  make the same changes to buddhavipassana/assets/css/carousel.css
- [x] push your changes back to dev1 branch in a commit for only this issue

**Comment by rahyoung** [comment]
- [x] You need to add the commit to the task

**Comment by rahyoung** [comment]
- [x] update to latest version of dev1 branch
- [x] Please look at the vertical spacing of the text next to each photo on buddhavipassana/overview.html. Please adjust the spacing on projects.html to match the spacing on overview.html
- [x] push changes in a commit for this issue only to dev1 branch
- [x] add commit to this issue

**Comment by dynamicdreamz1** [comment]
> * [x]  You need to add the commit to the task
=>**All changes is already done and push on dev1 branch**


> * [x]  update to latest version of dev1 branch
> * [x]  Please look at the vertical spacing of the text next to each photo on buddhavipassana/overview.html. Please adjust the spacing on projects.html to match the spacing on overview.html
> * [x]  push changes in a commit for this issue only to dev1 branch
> * [x]  add commit to this issue
=>**All changes is done and push on dev1 branch**
