### ISSUE TITLE
Design pull-down third level menus for teachers page

### ISSUE THREAD

**Issue by rahyoung** [onewaypath/onewaypath.com-bootstrap#8]
- [x] Ensure you are working on the latest version of dev1 branch
- [x] There are two sub-items for the teachers page. Thinking of mobile, we need a way to show this to the user from the submenu. One approach is to ad a pull-down option to the teachers item on the sub-menu. However, when the user pulls down it will cover the text below. Therefore, I think the pull down selection needs to shift the all the text on the screen down and then display the options to with left align. Please design this and add the feature to all the submenu on all pages. The structure of the teachers menu should be as follows:
- Teachers
       - Spiritual Leaders (links to spiritual-leaders.html)
       - Resident Teachers (links to teachers.html)
- [x] On desktop, you can just install a simple pull down option

- [x] Push your changes back to the dev1 branch with a commit for this issue only

**Comment by dynamicdreamz1** [comment]
Design pull-down third level menus for teachers page => Done and updated

**Comment by rahyoung** [comment]
It doesn't work on mobile.

- [x] Update to latest version of dev1 branch
- [x] Ensure page shifts down to reveal menu
- [x] Make sure you test on mobile before committing and pushing your changes. 

![image](https://user-images.githubusercontent.com/50812666/167615516-27eb2680-8efb-4988-a40b-40e79872cf6b.png)

![image](https://user-images.githubusercontent.com/50812666/167615534-b228d594-d189-4b65-92c5-bbf7ca4b5148.png)

**Comment by dynamicdreamz1** [comment]
**This is done we have chack in sfari and ios.**

**Comment by rahyoung** [comment]
Now you are covering the page text. 
- [x] Please shift page text down when drop down selected on mobile 

![image](https://user-images.githubusercontent.com/50812666/167790042-2f585986-3576-493b-a3d1-4a6dfd5fc541.png)

**Comment by dynamicdreamz1** [comment]
This is done => https://github.com/onewaypath/onewaypath.com-bootstrap/commit/74f64efb1dea3881b7778b67dc8d709e8f4a7a5f
